server:
  port: 8889
spring:
  devtools:
    restart:
      enabled: true
  cache:
    redis:
      # Redis缓存数据统一设置有效期为1分钟
      time-to-live: 60000
  redis:
    host: 192.168.56.101
    port: 6379
    password: 654321
    database: 0 # 数据库索引，默认0
    timeout: 5000  # 连接超时，单位ms
    # 哨兵模式
    sentinel:
      master: mymaster
      nodes: 192.168.56.101:26379,192.168.56.101:26380 # 哨兵的IP:Port列表
    # 集群模式
    #    cluster:
    #      nodes: 192.168.40.201:7100,192.168.40.201:7200,192.168.40.201:7300,192.168.40.201:7400,192.168.40.201:7500,192.168.40.201:7600
    #      max-redirects: 3  # 重定向的最大次数
    lettuce: # jedis或lettuce, 连接池配置，springboot2.0中使用jedis或者lettuce配置连接池，默认为lettuce连接池
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池分配连接最大阻塞等待时间（阻塞时间到，抛出异常。使用负值表示无限期阻塞）
        max-idle: 8 # 连接池中的最大空闲连接数
        min-idle: 0 # 连接池中的最小空闲连接数
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: test
      password: 123456
      url: jdbc:mysql://192.168.56.101:3306/springbootstudy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      ######################## 数据源其他配置 ########################
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #是否缓存preparedStatement 也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 20
      #连接池中的minIdle数量以内的连接，闲置时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      #keep-alive: true
      #Spring 监控，利用aop 对指定切面的执行时间，jdbc数进行记录
      aop-patterns: tk.fulsun.demo.service.*,tk.fulsun.demo.dao.*,tk.fulsun.demo.controller.*,tk.fulsun.demo.mapper.*
      filters: stat,wall,log4j
      filter:
        log4j:
          enabled: true
          statement-log-enabled: true
          connection-log-enabled: false
          result-set-log-enabled: true
      web-stat-filter:
        enabled: true
        #过滤所有url
        url-pattern: /*
        #排除一些不必要的url
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
        #开启session统计功能
        session-stat-enable: true
        #session的最大个数,默认1000
        session-stat-max-count: 1000
mybatis:
  # 映射实体地址
  type-aliases-package: tk.fulsun.demo.model
  # xml配置文件地址
  mapper-locations: classpath:mapper/*.xml
  # mybatis全局配置,与configuration 不能同时存在
  # config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    #当传入null的时候对应的jdbctype
    jdbc-type-for-null: null