server:
  port: 8071

logging:
  file: #配置日志输出的文件
    path: logs/seckill-gateway-service.log
  pattern:
    console: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"
    file: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"
  level:
    root: INFO
    tk.fulsun.order: DEBUG

spring:
  application:
    name: seckill-gateway-service
  cache:
    redis:
      # Redis缓存数据统一设置有效期为1分钟
      time-to-live: 60000
  redis:
    host: 192.168.56.101
    port: 6379
    password: 654321
    database: 0 # 数据库索引，默认0
    timeout: 5000  # 连接超时，单位ms
    ssl: false
    # 哨兵模式
    #    sentinel:
    #      master: mymaster
    #      nodes: 192.168.56.101:26379,192.168.56.101:26380 # 哨兵的IP:Port列表
    # 集群模式
    #    cluster:
    #      nodes: 192.168.40.201:7100,192.168.40.201:7200,192.168.40.201:7300,192.168.40.201:7400,192.168.40.201:7500,192.168.40.201:7600
    #      max-redirects: 3  # 重定向的最大次数
    lettuce: # jedis或lettuce, 连接池配置，springboot2.0中使用jedis或者lettuce配置连接池，默认为lettuce连接池
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池分配连接最大阻塞等待时间（阻塞时间到，抛出异常。使用负值表示无限期阻塞）
        max-idle: 8 # 连接池中的最大空闲连接数
        min-idle: 0 # 连接池中的最小空闲连接数
  datasource:
    schema:
      - classpath:db/schema.sql
    data:
      - classpath:db/data.sql
#    url: jdbc:h2:mem:testdbsa
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    username: test
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/springbootstudy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  # H2配置
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
#        trace: true
mybatis:
  # 映射实体地址
  type-aliases-package: tk.fulsun.gateway.common.dao.dataobject
  # xml配置文件地址
  mapper-locations: classpath:mapper/*.xml
  # mybatis全局配置,与configuration 不能同时存在
  # config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    #当传入null的时候对应的jdbctype
    jdbc-type-for-null: null
    #用map接受查询结果时，会自动将查询结果为null的字段忽略
    #查询到0条记录时 会接收到一个所有key值都为null的map
    #只查询一个字段，而用map接收 会接收到一个为null的map
    call-setters-on-nulls: true

rocketmq:
  nameserver: 192.168.56.101:9876
seckill:
  order:
    query:
      url: 127.0.0.1:8071