server:
  port: 8080

logging:
  file: #配置日志输出的文件
    path: logs/seckill-gateway-service.log
  pattern:
    console: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"
    file: "%-12(%d{yyyy-MM-dd HH:mm:ss.SSS}) |-%-5level [%thread] %c [%L] -| %msg%n"
  level:
    root: INFO
spring:
  application:
    name: demo-flyway
  datasource:
    #    schema:
    #      - classpath:db/schema.sql
    #    data:
    #      - classpath:db/data.sql
    url: jdbc:h2:mem:testdbsa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # H2配置
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true